version: '3'
services:
 mongodb:
  image: mongo:3.0
  container_name: q1-mongodb
  network_mode: "host"
  healthcheck:
   test: ["CMD", "mongo", "--eval", "db.stats()"]

 Nodejs:
  image: node:6.9.1
  container_name: q1-nodejs
  working_dir: /home/app
  volumes:
   - ./nodeproject:/home/app
  network_mode: "host"
  command: ["sh","-c","npm start"]
  depends_on:
   mongodb:
     condition: service_healthy 

networks:
   q1app:
    driver: bridge
